### ISSUE TITLE
Issue backgroundColor and highLightPerTapEnabled

### ISSUE THREAD

**Issue by setime** [SunPointed/MPFlutterChart#10]
If the background color is set and highlight per tag is enabled, the highlighting sets the pie chart to the background color.

**Comment by SunPointed** [comment]
I test what you said , it looks the background color did not influence pie chart highlighting. You can install demo app directly(do not use hot restart) and have a try.If the problem persists, Can you upload your PieChart setting and paste a picture about happened?
