### ISSUE TITLE
Can getFormattedValue1 provider the entry parameter or override other function？

### ISSUE THREAD

**Issue by chenparty** [SunPointed/MPFlutterChart#104]
作者您好：
    感谢您开发的这个伟大的库，我使用的linechart。x轴需要显示时间，但是entry的x我不想直接使用时间戳，这会导致某段时间无数据则显示一条不能点击的长线。
所以我的entry定义为：(x:index, y:value, data:timestamp)。
但是x轴显示内容通过xAxis.setValueFormatter(XValValueFormatter());
重写getFormattedValue1(double value)方法，value为index即索引，
我需要使用entry.data来显示时间，我尝试了getFormattedValue3，但是好像不起作用，我不知道getFormattedValue2和getFormattedValue3有什么意义，没有找到更多的文档来明白这件事。
我可以怎么做呢，期待您的答复。

**Comment by SunPointed** [comment]
sorry getFormattedValue3 getFormattedValue2 have no use yet, you may keep xaxis value and timestamp's relationship by your own.
