### ISSUE TITLE
onNothingSelected method of OnChartValueSelectedListener is called when tapped outside area of piechart ( container in which piechart added)

### ISSUE THREAD

**Issue by anwar25** [SunPointed/MPFlutterChart#105]
I have added OnChartValueSelectedListener to piechart . 
When i unhighlight any value of piechart onNothingSelected callback gets called . but it is getting 
called if i tap outside of the pichart area also .

**Comment by SunPointed** [comment]
The chart in fact a rect area,  tap in this area will trigger onNothingSelected
