### ISSUE TITLE
Provision to customize tooltip (which is by default like x,y).

### ISSUE THREAD

**Issue by MohdFaizan123** [SunPointed/MPFlutterChart#106]
Hi, Can we add custom tooltip for the graph, like the one with custom label and other customization. Thanks

**Comment by keskink** [comment]
you should work around ,
class fxChartMarker implements IMarker {
  ...
  ...
}

you should call like this

mFlght.chartController.marker = fxChartMarker(textColor:Colors.black54, backColor:Colors.black12, fontSize: 12.0, cnt: mFlght.chartController);

**Comment by SunPointed** [comment]
@MohdFaizan123  keskink is right
