### ISSUE TITLE
enableDashedLine move  problem

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#112]
problem line after refresh and move CombinedChart
```
    datasetMovingAvrage.enableDashedLine(5,5, 10);
    datasetMovingAvrage.setMode(Mode.CUBIC_BEZIER);
```

this video my problem
https://streamable.com/x9q87c
[](https://streamable.com/x9q87c)

**Comment by SunPointed** [comment]
hi @m2faridi , when I translate this lib, the flutter not support dash line yet, I use a third lib named path_drawing, the dash line move is caused by this lib.
