### ISSUE TITLE
Candle bugs

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#116]
1.Candles without a body do not show
2.Candles need border Color for body Increasing and Decreasing

**Comment by quanbui1998** [comment]
Have you found solution for this issue? @m2faridi

**Comment by m2faridi** [comment]
fix by this code
candleDataSet.setNeutralColor(ColorUtils.BLACK)
@quanbui1998

**Comment by quanbui1998** [comment]
@m2faridi I want to draw stroke same as
![image](https://user-images.githubusercontent.com/48360868/96326518-7f600680-105b-11eb-8c48-fcf27a6e483f.png)

Do you have a solution?
