### ISSUE TITLE
I want set x axis label, like type of '00:00'

### ISSUE THREAD

**Issue by tzt1994** [SunPointed/MPFlutterChart#17]

**Comment by SunPointed** [comment]
It seems in example, BarChart basic demo is what you want, extends ValueFormatter add set it to x axis.

**Comment by tzt1994** [comment]
where is exmaple project？ and  I created class extends ValueFormatter add set it to xAxis, but is not right ?

this is my code:
String getLabel(double value) {
  var yu = int.parse(value.toString()) % 60;
  var zheng = int.parse(value.toString()) / 60;
  StringBuffer stringBuffer = StringBuffer();
  if (zheng <= 9) {
    stringBuffer.write('0' + zheng.toString());
  } else {
    stringBuffer.write(zheng.toString());
  }

  stringBuffer.write(':');

  if (yu <= 9) {
    stringBuffer.write('0' + yu.toString());
  } else {
    stringBuffer.write(yu.toString());
  }

  print('格式化: $value \t 返回值${stringBuffer.toString()}');

  return stringBuffer.toString();
}

class DateValueFormatter extends ValueFormatter{
  @override
  String getFormattedValue1(double value) {
    return getLabel(value);
  }
}

set this ValueFormatter 
_lineChartController = LineChartController(......)
_lineChartController.xAxis.setValueFormatter(DateValueFormatter());

**Comment by s349856186** [comment]
@tzt1994 Have you finished this effect? How to do？
