### ISSUE TITLE
发现一个问题：如果数据列表中有多个BarEntry的y值是相同的如图1，会出现图2的现象，即有多条相同的横线，请问这种情况如何处理，谢谢

### ISSUE THREAD

**Issue by manburenshenglu** [SunPointed/MPFlutterChart#18]
图1：![image](https://user-images.githubusercontent.com/13146756/71300763-e462b580-23d2-11ea-9ed1-f282e1fd2d4b.png)
图2：
![image](https://user-images.githubusercontent.com/13146756/71300807-48857980-23d3-11ea-9b5b-4aa496bfdab9.png)

**Comment by manburenshenglu** [comment]
![88888888888888](https://user-images.githubusercontent.com/13146756/71301067-f134d880-23d5-11ea-9c59-7a6e5f717d4d.jpg)

**Comment by SunPointed** [comment]
![image](https://user-images.githubusercontent.com/9999781/71330869-4b66a280-256a-11ea-9b50-b39e1ce9fe42.png)
q去看下例子中bar basic的这里，你没有设置自己的valueformat，使用默认的会转化为整数，比1小所以是两个0

**Comment by manburenshenglu** [comment]
是的楼主，我也发现了。想问一下如果X轴需求要求是整数，遇到这种问题该怎么处理，谢谢

**Comment by SunPointed** [comment]
都可以设置valueFormatter，可以随便转
