### ISSUE TITLE
how to filter autoScaleMinMaxEnabled in ChartCombined

### ISSUE THREAD

**Issue by mfaridi** [SunPointed/MPFlutterChart#21]
i need filter autoScaleMinMaxEnabled only for CandleDataSet inside ChartCombined

![Image of Yaktocat](https://i.ibb.co/xfJFSLq/Untitled.jpg)
**thank you**

**Comment by mfaridi** [comment]
[https://ibb.co/NmZT6C2](url)

**Comment by SunPointed** [comment]
hi, all data sets in combined chart use same x axis and y axis, autoScaleMinMaxEnabled will influence axis, so it seem impossible to achieve this.

**Comment by m2faridi** [comment]
How can I filter only candles?
Please find a way to do this
