### ISSUE TITLE
how to call chart Scroll Change in MPFlutterChart

### ISSUE THREAD

**Issue by mfaridi** [SunPointed/MPFlutterChart#22]
How to Call Event Scroll Change in Chart?

**Comment by mfaridi** [comment]
How to Call Event Scroll Change in Chart?

**Comment by SunPointed** [comment]
what mean call event scroll change? Now I offer a callback when touch event happen, you can see BarCahrt Basic demo in example，

**Comment by mfaridi** [comment]
i need this code for chart

`myScrollView.setOnScrollChangeListener(new NestedScrollView.OnScrollChangeListener() {
        @Override
        public void onScrollChange(NestedScrollView v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
            Log.d("ScrollView","scrollX_"+scrollX+"_scrollY_"+scrollY+"_oldScrollX_"+oldScrollX+"_oldScrollY_"+oldScrollY);
            //Do something
        }
    });`
