### ISSUE TITLE
[Bug] posation y in chart

### ISSUE THREAD

**Issue by mfaridi** [SunPointed/MPFlutterChart#27]
position y in ChartCombined chart not correct
`double y=controller.getValuesByTouchPoint(controller.viewPortHandler.contentRight(),controller.viewPortHandler.contentBottom(), AxisDependency.RIGHT).y`

**Comment by SunPointed** [comment]
![image](https://user-images.githubusercontent.com/9999781/71759735-71862e00-2eec-11ea-9049-b7bf791244f1.png)
hi, I think its right, it convert the local coordinate system（where the origin is view‘s left and top）to the chart coordinate system (where the origin is chart's (0, 0) point).

**Comment by mfaridi** [comment]
@override
  void onTapDown(double x, double y) {
  if(select==0){
      select_x1=controller.getValuesByTouchPoint(x, y, AxisDependency.RIGHT).x;
      select_y1=controller.getValuesByTouchPoint(x, y, AxisDependency.RIGHT).y;
    }
}
select_x1 it's correct
select_y1 it's not correct
