### ISSUE TITLE
[bug] problem in autoScale

### ISSUE THREAD

**Issue by mfaridi** [SunPointed/MPFlutterChart#28]
i create to custom autoScale for combind follow Candle data

https://streamable.com/wfqkw
[](https://streamable.com/wfqkw)
```
  @override
  void onMoveUpdate(double x, double y) {
    double xmin=controller.getValuesByTouchPoint(controller.viewPortHandler.contentLeft(),controller.viewPortHandler.contentBottom(), AxisDependency.RIGHT).x;
    double xmax=controller.getValuesByTouchPoint(controller.viewPortHandler.contentRight(),controller.viewPortHandler.contentBottom(), AxisDependency.RIGHT).x;

    double ymin=controller.getValuesByTouchPoint(controller.viewPortHandler.contentRight(),controller.viewPortHandler.contentBottom(), AxisDependency.RIGHT).y;
    double ymax=controller.getValuesByTouchPoint(controller.viewPortHandler.contentRight(),controller.viewPortHandler.contentTop(), AxisDependency.RIGHT).y;
    double candle_y_max=0;
    double candle_y_min=double.maxFinite;

    for(int i=xmin.toInt();i<xmax;i++){
      if(i>=0 && i< entries.length){
        if(candle_y_min>entries[i].shadowLow){
          candle_y_min=entries[i].shadowLow;
        }
        if(candle_y_max<entries[i].shadowHigh){
          candle_y_max=entries[i].shadowHigh;
        }
      }

    }
    double space=0.20;
    controller.moveViewTo(xmin,(candle_y_min+((ymax-ymin)/2))-space, AxisDependency.RIGHT);
    controller.setVisibleYRange(0.0,(candle_y_max-candle_y_min)+(space),AxisDependency.RIGHT);
    
  }
```

**Comment by SunPointed** [comment]
hi, when you want to update ui call controller.state.setStateIfNotDispose to do it

**Comment by SunPointed** [comment]
in your video it seems worked, so what's your problem?

**Comment by mfaridi** [comment]
The code works fine but it is very time consuming
Like video sometimes it goes somewhere else and returns immediately

**Comment by mfaridi** [comment]
The code works fine but it is very time consumingLike video sometimes it goes somewhere else and returns immediately
    On Saturday, January 4, 2020, 09:41:29 AM GMT+3:30, SunPointed <notifications@github.com> wrote:  
 
 
in your video it seems worked, so what's your problem?

**Comment by mfaridi** [comment]
fixed
i need replace code
BEFORE
`    
    controller.moveViewTo(xmin, (candle_y_min + ((ymax - ymin) / 2)) - space,
        AxisDependency.RIGHT);

controller.setVisibleYRange(
        0.0, (candle_y_max - candle_y_min) + (space), AxisDependency.RIGHT);`
AFTER
`    controller.setVisibleYRange(
        0.0, (candle_y_max - candle_y_min) + (space), AxisDependency.RIGHT);

    controller.moveViewTo(xmin, (candle_y_min + ((ymax - ymin) / 2)) - space,
        AxisDependency.RIGHT);`

**Comment by mfaridi** [comment]
How do I get this function?
i need call for replace custom scale
`  void compute() {
    if (_autoScaleMinMaxEnabled) {
      autoScale();
    }`
