### ISSUE TITLE
add onScrollListener

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#29]
please add onScrollListener for Controller

**Comment by SunPointed** [comment]
Did OnTouchEventListener  unmet your demand？I think onMoveUpdate(double x, double y) equals to scroll

**Comment by mfaridi** [comment]
NO, I need to always be aware
 onMoveUpdate When we touch, it works

**Comment by SunPointed** [comment]
so，how the chart can auto scroll， I don’t know the scene

**Comment by crizant** [comment]
> Did OnTouchEventListener unmet your demand？I think onMoveUpdate(double x, double y) equals to scroll

Actually no. If we drag and release the chart, the chart has a intertia (惯性) will continue to scroll for a little distance. We cannot get the last position it scrolled to.

**Comment by SunPointed** [comment]
#54
