### ISSUE TITLE
柱状图点击显示问题

### ISSUE THREAD

**Issue by inprise1980** [SunPointed/MPFlutterChart#30]
目前，点击柱状图的某个柱，顶部会显示标签，内容为x轴值,y轴值， 如"1，3.12"、“2，4.1” ，1为x轴，3.12为y轴值，请问如何设置成只显示y轴值，如"3.12"，不显示x轴的值？

**Comment by SunPointed** [comment]
现在barchart使用的是BarChartMarker，你可以参照逻辑实现你自己的Marker并传入controller就行

**Comment by inprise1980** [comment]
我用的是分支localPosition-support这个版本，不是新版，这个版本是因为我用的flutter版本为1.5.4，所以前几个月前让你帮忙弄的分支。

**Comment by inprise1980** [comment]
这个版本有解决方法吗
