### ISSUE TITLE
还是柱状图点击显示问题

### ISSUE THREAD

**Issue by inprise1980** [SunPointed/MPFlutterChart#31]
问题如issues30
我用的是分支localPosition-support这个版本，不是新版，这个版本是因为我用的flutter版本为1.5.4，所以前几个月前让你帮忙弄的分支。
这个版本有解决方法吗？

**Comment by SunPointed** [comment]
这个版本我没更新了，我看了下有Controller，解决方法是一样的。实现自己的IMarker并传入就行了，你可以看下LineChartMarker
