### ISSUE TITLE
LineChart can't hide grid lines

### ISSUE THREAD

**Issue by te8uekm12** [SunPointed/MPFlutterChart#32]
Hello,
I have a problem with hiding grid lines. Here is my widget. Could you help me with this?

  _controller.xAxis.enabled=false;
  _controller.axisLeft.enabled=false;
  _controller.axisRight.enabled=false;
  _controller.xAxis.drawGridLines=false;
  _controller.axisLeft.drawGridLines=false;
  _controller.axisRight.drawGridLines=false;

`
class DynamicLineChart extends StatefulWidget {
  List<Entry> _chartEntryList;
  DynamicLineChartConfiguration _configuration;

  DynamicLineChart(this._chartEntryList,this._configuration);

  @override
  State<StatefulWidget> createState() =>_DynamicLineChartState();
}

class _DynamicLineChartState extends State<DynamicLineChart> {
  LineChartController _controller;

  DynamicLineChartConfiguration get _configuration=>widget._configuration;
  List<Entry> get _chartEntryList=>widget._chartEntryList;

  @override
  void initState() {
    var desc = Description()..enabled = false;
    _controller = LineChartController(
        noDataText: _configuration.noDataText,
        drawGridBackground: _configuration.drawGridBackgroud,
        dragXEnabled: true,
        dragYEnabled: true,
        scaleXEnabled: true,
        scaleYEnabled: true,
        selectionListener: _configuration.selectionListener,
        pinchZoomEnabled: true,
        drawBorders: true,
        backgroundColor: Colors.white,
        customViewPortEnabled: true,
        description: desc);
    _controller.doneBeforePainterInit();
    _controller.data = LineData();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    _setEntryList(_chartEntryList);
    return LineChart(_controller);
  }

  void _setEntryList(List<Entry> values) {
    if(values==null || values.length==0) return;
    LineDataSet set = new LineDataSet(values, "TODO -> Total: ${values.length}");
      set.setLineWidth(_configuration.lineWidth);
      set.setCircleRadius(_configuration.circleRadius);
      set.setColor1(_configuration.lineColor);
      set.setCircleColor(_configuration.circleColor);
      set.setHighLightColor(_configuration.highLightColor);
      set.setValueTextSize(_configuration.valueTextSize);
      set.setValueTextColor(_configuration.valueTextColor);
      set.setMode(_configuration.mode);
      _controller.data.clearValues();
      _controller.data.addDataSet(set);
      _controller.setVisibleXRangeMaximum(_configuration.visibleXRangeMaximum);
      _controller.moveViewTo(_controller.data.getEntryCount().toDouble(), 0, AxisDependency.LEFT);
      _controller.autoScaleMinMaxEnabled=false;
      _controller.xAxis.enabled=false;
      _controller.axisLeft.enabled=false;
      _controller.axisRight.enabled=false;
      _controller.xAxis.drawGridLines=false;
      _controller.axisLeft.drawGridLines=false;
      _controller.axisRight.drawGridLines=false;
      _controller.axisLeft.gridColor=Colors.white;
  }
}
`

**Comment by SunPointed** [comment]
LineChartController have argments like xxxSettingFunction, you can do these axis setting things in these callback functions.  controller‘s najority attributes only init before chart is show（see doneBeforePainterInit function）

**Comment by ezmegy** [comment]
I'm trying to achieve the same thing: hide the grid lines.

Doing this:
`LineChartController(
      ...
      xAxisSettingFunction: (xAxis, controller) {
        xAxis.drawGridLinesBehindData = false; // no effect
        xAxis.drawGridLines = false; // no effect
        xAxis.drawLabels = false; // this works however
      },
    );`

seemingly does not work.

@SunPointed Any ideas why or what I am missing here maybe?

Cheers
