### ISSUE TITLE
LineActionState 找不到这个类

### ISSUE THREAD

**Issue by kazeik** [SunPointed/MPFlutterChart#33]
LineActionState 在0.1.2中找不到这个类。
另外图表区域不支持左右平行滑动吗？

**Comment by SunPointed** [comment]
LineActionState是example用例里面的，和这个库无关。左右平行滑动这个没太理解到意思？

**Comment by kazeik** [comment]
就是按着屏不松，譬如在line图表上，按着屏幕不松左右滑动时，它的焦点跟着移动。

**Comment by SunPointed** [comment]
如果放大后当前显示不下所有数据，是支持拖着滑动的，你可以试试
