### ISSUE TITLE
How to make the radar-chart position to top by own?

### ISSUE THREAD

**Issue by isshun226** [SunPointed/MPFlutterChart#35]
## Problem
I tried almost of the setter in ``RadarChartController``とfix the chart position but dosn`t effect.
There is any way to specified  the chart position?
and erase the title-label.

## What I tried
```dart
RadarChartController(
  ...
  legendSettingFunction: (legend, controller) {
    legend
      ...
      ..yOffset = (0);
  }
  ...
}
```

Use ``yOffset`` can specified the position, but cant move until the top.
I think this is caused by the title-label of the radar-chart.
Does anyone know how to solve this problem?

**Comment by SunPointed** [comment]
make legend enabled false may help
