### ISSUE TITLE
y-axis overflow

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#36]
I have noticed that in some datasets, the y-axis would overflow. You can see it overlapped with the content above:

![Simulator Screen Shot - iPhone Xs - 2020-02-05 at 13 32 11](https://user-images.githubusercontent.com/8337876/73813778-0053d680-481c-11ea-9b53-d0dbf230999c.png)

I have created a minimal repository to reproduce the issue:
https://github.com/crizant/mp_chart_issue

Any help is appreciated. Thanks!

**Comment by SunPointed** [comment]
hi, fix this in 0.1.3
