### ISSUE TITLE
Limit line label background color?

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#38]
Hi, I would like to set a background color for the label of limit line like:

![IMG_A68949A5FBE9-1](https://user-images.githubusercontent.com/8337876/73832522-4708f700-4843-11ea-87b6-ff1f13bc2707.jpeg)

Is it possible with this library?

**Comment by SunPointed** [comment]
now support this feature you can take a look at LimiteLine , but 1.4 is not publish yet ,fucking my contry's GFW

**Comment by crizant** [comment]
What do you mean by 1.4 is not published?
Limiteline is another library?
Because I don't see the option to add label background for LimitLine.

**Comment by crizant** [comment]
我还是说中文吧，那个Limit line 的标籤有橙色的背景能做到吗？
