### ISSUE TITLE
Line chart gradient fill

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#40]
In MPAndroidChart it is possible to draw gradient fill in line charts, would you please add this feature too?

**Comment by SunPointed** [comment]
the flutter seem's not support this feature yet, I have a look later...

**Comment by crizant** [comment]
I have done some research, here is the way to implement gradient fill:

```dart
final Gradient gradient = LinearGradient(
  begin: Alignment.topCenter,
  end: Alignment.bottomCenter,
  colors: [
    color1,
    color2,
  ],
);
final Rect bounds = filledPath.getBounds();
c.drawPaint(
  Paint()
    ..shader = gradient.createShader(
      Rect.fromLTWH(
        bounds.left,
        bounds.top,
        bounds.width,
        bounds.height,
      ),
    ),
);
```

**Comment by farhadsaberi** [comment]
hi, how to draw gradient fill in line charts?

**Comment by SunPointed** [comment]
@crizant  sorry for late , already add add Gradient to line chart and radar chart, you can check the line chart basic and radar demo
