### ISSUE TITLE
TextPainter.paint called when text geometry was not yet calculated.

### ISSUE THREAD

**Issue by izzabellerina** [SunPointed/MPFlutterChart#41]
Hello everyone  , I now create line chart. sorry that I am not strong English. I have some problem which I don't know why my console call "TextPainter.paint called when text geometry was not yet calculated." while i was tapping the chart  ,the marker view didn't show also. Does anyone know what to do for fixing? 
This is my Code.

class CreateTest{

  CreateTest();
  Widget returnLineChart() {
    var desc = Description()..enabled = false;
    var dataPoint = List<Entry>();
    List<ILineDataSet> dataSets = List();
    dataPoint.add(Entry(x: 1, y: 2));
    dataPoint.add(Entry(x: 2, y: 3));
    dataPoint.add(Entry(x: 3, y: 4));
    dataPoint.add(Entry(x: 4, y: 5));
    dataPoint.add(Entry(x: 5, y: 6));
    dataPoint.add(Entry(x: 6, y: 7));
    dataPoint.add(Entry(x: 7, y: 8));
    dataPoint.add(Entry(x: 8, y: 9));
    dataPoint.add(Entry(x: 9, y: 1));
    LineDataSet set1;
    set1 = LineDataSet(dataPoint, "DataSet 1");
    set1.setDrawIcons(false);
    set1.enableDashedLine(10, 5, 0);
    set1.setColor1(ColorUtils.BLACK);
    set1.setCircleColor(ColorUtils.BLACK);
    set1.setHighLightColor(ColorUtils.PURPLE);
    set1.setLineWidth(1);
    set1.setCircleRadius(3);
    set1.setDrawCircleHole(false);
    set1.setFormLineWidth(1);
    set1.setFormLineDashEffect(DashPathEffect(10, 5, 0));
    set1.setFormSize(15);
    set1.setValueTextSize(9);
    set1.enableDashedHighlightLine(10, 5, 0);
    set1.setDrawFilled(true);
    set1.setFillColor(ColorUtils.FADE_RED_END);
    dataSets.add(set1);
     var controller = LineChartController(
        axisLeftSettingFunction: (axisLeft, controller) {
          axisLeft
            ..drawLimitLineBehindData = true
            ..enableGridDashedLine(10, 10, 0)
            ..enableAxisLineDashedLine(5, 5, 0)
            ..setAxisMaximum(10)
            ..setAxisMinimum(1);
        },
        axisRightSettingFunction: (axisRight, controller) {
          axisRight.enabled = (false);
        },
        legendSettingFunction: (legend, controller) {
          legend.shape = (LegendForm.LINE);
        },
        xAxisSettingFunction: (xAxis, controller) {
          xAxis
            ..drawLimitLineBehindData = true
            ..enableAxisLineDashedLine(5, 5, 0)
            ..enableGridDashedLine(10, 10, 0);
        },
        drawGridBackground: false,
        backgroundColor: ColorUtils.WHITE,
        dragXEnabled: true,
        dragYEnabled: true,
        scaleXEnabled: true,
        scaleYEnabled: true,
        pinchZoomEnabled: true,
        description: desc);
    controller.setViewPortOffsets(16, 16, 16, 16);
    controller.data = LineData.fromList(dataSets);
    return LineChart(controller);
  }

}

**Comment by SunPointed** [comment]
my error is The following assertion was thrown building Builder(dirty):
type 'List<dynamic>' is not a subtype of type 'List<Entry>'

change this code
`
var dataPoint = List<Entry>();
List dataSets = List<LineDataSet>();
`
the result is right
![image](https://user-images.githubusercontent.com/9999781/74116856-56e05c80-4bf0-11ea-880b-5d2a1a47f7f5.png)

**Comment by qzcsfchh** [comment]
Hi, I'm an android developer,  and I got this problem when using PieChart, your suggestion for @izzabellerina seems not work for me. My code was like:

  PieData _createPieData(List<EntryBean> beans) {
    List data = beans.map((b) {
      return PieEntry(value: b.problemNum?.toDouble() ?? 0.0, label: b.name);
    }).toList();
    return PieData(PieDataSet(data, '')
      ..setValueFormatter(_percentFormatter)
      ..setValueTextSize(11)
      ..setValueTextColor(Colors.white)
      ..setDrawIcons(false)
      ..setDrawValues(false)
      ..setColors1(PIE_COLORS)
      ..setSliceSpace(2));
  }

can u tell me what went wrong in the code please? thanks in advance for your greate work

ps: version of mp_chart is ^1.0.7

**Comment by ekasetiawans** [comment]
Hi, i'm facing the same issue. I using `mp_chart: ^0.1.8`.
here is my stacktrace :

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
TextPainter.paint called when text geometry was not yet calculated.

Please call layout() before paint() to position the text before painting it.
The relevant error-causing widget was
    PieChart 
lib/widgets/statistik1.dart:124
When the exception was thrown, this was the stack
#0      TextPainter.paint.<anonymous closure> 
package:flutter/…/painting/text_painter.dart:589
#1      TextPainter.paint 
package:flutter/…/painting/text_painter.dart:595
#2      ChartPainter.drawDescription 
package:mp_chart/…/painter/painter.dart:270
#3      PieChartPainter.onPaint 
package:mp_chart/…/painter/pie_chart_painter.dart:193
#4      ChartPainter.paint 
package:mp_chart/…/painter/painter.dart:249
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#f88f5
RenderObject: RenderCustomPaint#f88f5
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=342.0, h=228.0)
    size: Size(342.0, 228.0)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
TextPainter.paint called when text geometry was not yet calculated.
The relevant error-causing widget was
    BarChart 
lib/widgets/statistik2.dart:164
════════════════════════════════════════════════════════════════════════════════
```

**Comment by Alishgiri** [comment]
After creating text painter don't forget to call textPainter.layout()
