### ISSUE TITLE
The limit label y position is not correct

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#44]
When we set label position to `LimitLabelPosition.LEFT_CENTER` and `LimitLabelPosition.RIGHT_CENTER`, the y position is not aligned center.

I have created a pull request #43 to fix this issue.

Before:
![Simulator Screen Shot - iPhone Xs - 2020-02-07 at 15 46 11](https://user-images.githubusercontent.com/8337876/74010686-06cf8300-49c1-11ea-8375-3eb24764befe.png)

After:
![Simulator Screen Shot - iPhone Xs - 2020-02-07 at 15 45 45](https://user-images.githubusercontent.com/8337876/74010690-0cc56400-49c1-11ea-835e-94c0f9dfd8b7.png)

**Comment by SunPointed** [comment]
merged
