### ISSUE TITLE
Info background color?

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#45]
Currently the "No chart data available" screen is white in background.
Would you please apply the value of `backgroundColor` to it, or add an option `infoBackgroundColor`, so that we can customize the style of it?

<img width="348" alt="螢幕截圖 2020-02-07 下午11 23 51" src="https://user-images.githubusercontent.com/8337876/74041812-5170ef80-4a01-11ea-9590-d2e6757fde5f.png">

**Comment by SunPointed** [comment]
infoBgColor is added in controller wish its you wanted

**Comment by crizant** [comment]
Thanks, when will it be published?
