### ISSUE TITLE
Change zoom level

### ISSUE THREAD

**Issue by valientegaston** [SunPointed/MPFlutterChart#46]
Hi! Thanks for this library!
How can I change zoom level from code?  I was reading that is changing viewport, but i cant.  
Thank you!

**Comment by SunPointed** [comment]
did you mean double tap zoom level ?

**Comment by crizant** [comment]
Try this:
```
final ViewPortHandler viewPortHandler = _controller.viewPortHandler;
    viewPortHandler.refresh(
      viewPortHandler.setZoom1(
        10,
        1.0,
      ),
    );
```

But I want to do the zooming once the chart is drawn, and I don't know how.

**Comment by valientegaston** [comment]
Thank you! It works!

**Comment by m2faridi** [comment]
controller.setScaleMinima(10, 1);
