### ISSUE TITLE
LongPress events?

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#47]
Please consider adding `onLongPressStart`, `onLongPressMoveUpdate`, and `onLongPressEnd` events to `OnTouchEventListener`.

Because I want to implement like this:
On simple drag => move the chart
On long press drag => move the highlight marker

**Comment by SunPointed** [comment]
Can expose OptimizedGestureDetector's OpsDragXXXCallback help this?

**Comment by crizant** [comment]
Yes but I also need `onLongPressStart` and `onLongPressEnd` to display and hide the drag indicator on long press down and long press up.

**Comment by SunPointed** [comment]
BarLineScatterCandleBubbleController's OnTouchEventListener have DragEvent now, you can have a try
