### ISSUE TITLE
On viewport update listener

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#54]
This is an extension of #29 and #48. But the on touch listener only receives events when the finger is touching the screen.

1. When we scroll fast, the chart will continue to scroll for a little distance after the finger is not in contact with the screen.
2. If we programmatically modify the viewport, for example calling `painter.zoom()`, the on touch listener will not be notified.

It would be nice if there's a listener which is called once the chart is translated and scaled.

**Comment by SunPointed** [comment]
add ChartTransListener, if set this listener, it scale and translate method will called when the chart is translate or zoom. It may called with OnTouchListener together but It can handle the situation once the chart is translated and scaled. Please check If it what you wanted.
