### ISSUE TITLE
OnTouchEventListener gives wrong x and y values

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#58]
If the `valueType` of an `OnTouchEventListener` is set to `CHART`, the `x` and `y` value in events should be the chart value of the touch point, right?

But it is not. Not I have to use `valueType` `LOCAL` then `controller.getValuesByTouchPoint()` to get the value I tapped.

**Comment by SunPointed** [comment]
SCREEN means point in screen，LOCAL means point in chart view， CHART means point is converted by chart(some matrix calculation), these enums only use in OnTouchEventListener and use can choose witch type is needed. controller.getValuesByTouchPoint should input point in chart view.

**Comment by crizant** [comment]
But the `CHART` view gives incorrect values. 
If I tap on the top right hand corner of the chart, it gives `x: 322.0416564941406, y: -156.87722730848526`, and my chart doesn't have negative values.
