### ISSUE TITLE
0.1.5版本安装失败

### ISSUE THREAD

**Issue by Zheng-Shuo** [SunPointed/MPFlutterChart#61]
如题，pub get 时候提示：
Because chart_demo depends on mp_chart ^0.1.5 which doesn't match any versions, version solving failed.
pub get failed (1; Because chart_demo depends on mp_chart ^0.1.5 which doesn't match any versions, version solving failed.)

**Comment by SunPointed** [comment]
估计要翻墙，我这开了vpn是行的
