### ISSUE TITLE
Line chart filled color on flutter web

### ISSUE THREAD

**Issue by crizant** [SunPointed/MPFlutterChart#63]
On flutter web, only the last batch of dataset on line chart is filled with color.
For example, 146 entries, then only 146 - 128 = 18 entries are filled.

![螢幕截圖 2020-02-17 下午1 11 17](https://user-images.githubusercontent.com/8337876/74625447-42b7d480-5187-11ea-9c3b-0e7323dfe2b0.png)

I have created #62 to fix the issue. Feel free to correct me if I'm wrong.

**Comment by SunPointed** [comment]
thanks，merged
