### ISSUE TITLE
how to update LinechartController using scoket data?

### ISSUE THREAD

**Issue by parthpitorda** [SunPointed/MPFlutterChart#69]
can any one help me for the same!

**Comment by SunPointed** [comment]
when you get your data， update the corresponding LineDataSet in controller's data, you may take a look at dynamic demo

**Comment by parthpitorda** [comment]
@SunPointed Currently in X-axis the data is in order of 0,1,2,3....Now, instead of this I want to update X-axis like 4:20pm, 4:21 pm, 4:22 pm and so on. how can I achieve this in line chart controller. I saw your hourly demo, but in that only one specific time is there, X-axis is not updating minutes data.
