### ISSUE TITLE
how to update LinechartController using scoket data?

### ISSUE THREAD

**Issue by parthpitorda** [SunPointed/MPFlutterChart#70]
Currently in X-axis the data is in order of 0,1,2,3....Now, instead of this I want to update X-axis like 4:20pm, 4:21 pm, 4:22 pm and so on. how can I achieve this in line chart controller. I saw your hourly demo, but in that only one specific time is there, X-axis is not updating minutes data.
![pk](https://user-images.githubusercontent.com/58161217/75654319-79144a00-5c85-11ea-8d1f-d014147f1a46.jpg)

**Comment by SunPointed** [comment]
see bar cahrt basic demo, implement your own ValueFormatter
`..setValueFormatter(DayAxisValueFormatter(controller));`
