### ISSUE TITLE
How to disable zoom in and how to set fix zoom in Performance Line Chart?

### ISSUE THREAD

**Issue by hvbeladiya149** [SunPointed/MPFlutterChart#71]
I want to set a fixed zoom in the performance line chart. if that's not possible then I want to disable auto-zoom in that chart.

**Comment by SunPointed** [comment]
for disable, set controller's these value
scaleXEnabled: false,
scaleYEnabled: falsse,
pinchZoomEnabled: false,

for set a fixed zoom, use controller.painter.zoom method
