### ISSUE TITLE
edit and insert entery by index

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#72]
please add function for Edit and Insert Entry by index

like array
`List.insert(index,Entry)`
`List.edit(index,Entry)`

**Comment by SunPointed** [comment]
I try this yesterday. If the index exists in entry list, edit/update is ok (in most cases, it will update the Y value of the corresponding entry).But insert seems a little conflict, do this means entries in the list can't have the same interval in X value(before insert X values is [1.0, 2.0, 3.0 ...], after is [1.0, 1.5, 2.0, 3.0 ...]), is this you want?

**Comment by m2faridi** [comment]
yes

**Comment by SunPointed** [comment]
done. you can see realtime demo for update and dynamic demo's comment for insert
