### ISSUE TITLE
MAX zoom Size

### ISSUE THREAD

**Issue by parthpitorda** [SunPointed/MPFlutterChart#75]
how to set the max zoom size. the chart is zoom to xxxxx level.

**Comment by SunPointed** [comment]
controller.viewPortHandler.setMaximumScaleY
controller.viewPortHandler.setMaximumScaleX
this may help you

**Comment by parthpitorda** [comment]
not working.

**Comment by parthpitorda** [comment]
> controller.viewPortHandler.setMaximumScaleY
> controller.viewPortHandler.setMaximumScaleX
> this may help you

**Comment by m2faridi** [comment]
try this code
`            controller.setScaleMinima(size_scale * 2, 1);

            controller.viewPortHandler.refresh(
                controller.viewPortHandler.setZoom1(
                    size_scale * 2, 1));`
