### ISSUE TITLE
The following PieChart widgets` layout  is wrong, when Description.enable =  true.

### ISSUE THREAD

**Issue by Luozf12345** [SunPointed/MPFlutterChart#77]
Log:

The following assertion was thrown during paint():
I/flutter (11837): TextPainter.paint called when text geometry was not yet calculated.
I/flutter (11837): Please call layout() before paint() to position the text before painting it.
I/flutter (11837): 
……
I/flutter (11837): When the exception was thrown, this was the stack:
I/flutter (11837): #0      TextPainter.paint.<anonymous closure> (package:flutter/src/painting/text_painter.dart:572:9)
I/flutter (11837): #1      TextPainter.paint (package:flutter/src/painting/text_painter.dart:578:6)
I/flutter (11837): #2      ChartPainter.drawDescription (package:mp_chart/mp/painter/painter.dart:270:18)
I/flutter (11837): #3      PieChartPainter.onPaint (package:mp_chart/mp/painter/pie_chart_painter.dart:193:5)
I/flutter (11837): #4      ChartPainter.paint (package:mp_chart/mp/painter/painter.dart:249:5)
I/flutter (11837): #5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter (11837): #6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter (11837): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter (11837): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (11837): #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11837): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter (11837): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
……

Code:
  @override
  Widget build() {
    return Row(
      children: <Widget>[

        buildRing(),
        Container(
          color: C.red_ffb51701,
          width: px(400),
          height: px(400),
          child: GestureDetector(
            behavior: HitTestBehavior.translucent,
            child: Text("Test"),
            onTap: (){

              ToastM.show("点击了");
            },
          ),
        )
      ],
    );
  }

Widget buildRing() {

    Description description = Description();
    description.text = "desc";
    description.enabled = true;
    PieChartController controller = PieChartController(drawEntryLabels: false,legendSettingFunction: (legend, controller){
      // 去掉解释色块
      legend.enabled = false;
    },
      description: description,

      // 中间圆孔半径占比
      holeRadiusPercent: 80,
      // 中间透明圆环占比
      transparentCircleRadiusPercent:0,

      // 点击区域不高亮
      highLightPerTapEnabled: false,
      backgroundColor: C.yellow_ffffb81a,
      minOffset: 0,
    );

    // 创建PieEntry，添加进列表
    List<PieEntry> entries = [];
    for(int i = 1; i <= 5; i++){
      entries.add(PieEntry(value: i%2.0 +1,));
    }
    // 创建DataSet
    PieDataSet dataSet = PieDataSet(entries,"test");
    // 设置颜色
    List<Color> colors = [C.red_ffb51701,C.blue_ff1f77fd,C.green_ff00d0a2,C.yellow_fff2ad00,C.black_ff333333,];
    dataSet.setColors1(colors);

    // 不显示数值
    dataSet.setDrawValues(false);

    // 创建Data
    PieData data = PieData(dataSet);

    // 赋值给控制器
    controller.data = data;
    
    return Container(
      width: px(500),
      height: px(500),
      child: PieChart(controller),
    );
  }

**Comment by SunPointed** [comment]
fixed
