### ISSUE TITLE
'rotateEnabled = false' of PieChartController is not work.

### ISSUE THREAD

**Issue by Luozf12345** [SunPointed/MPFlutterChart#78]
I set 'rotateEnabled = false' for PieChartController ,but the PieChart can rotate still.Then, I modify the method _updateGestureRotation of PieRadarChartState, and it works normally.
`void _updateGestureRotation(double x, double y) {
    if(widget.controller.rotateEnabled) {
      double angle =
          widget.controller.painter.getAngleForPoint(x, y) - _startAngle;
      widget.controller.rawRotationAngle = angle;
      widget.controller.rotationAngle =
          Utils.getNormalizedAngle(widget.controller.rawRotationAngle);
    }
  }`

**Comment by SunPointed** [comment]
fixed, thanks.
