### ISSUE TITLE
Line Chart is not supporting landscape orientation

### ISSUE THREAD

**Issue by kushal-rathod1** [SunPointed/MPFlutterChart#80]
While changing orientation to landscape, charts are also flipped to downside.

**Comment by SunPointed** [comment]
like android:screenOrientation="portrait"，this you should do in your native code

**Comment by vivekkujur** [comment]
facing same problem.  line chart not support landscape orientation.
chart width is too small in landscape orientation .

how can i  show line chart in landscape orientation.
