### ISSUE TITLE
textColor not chaning any legent label colors. (still continue this issue.)

### ISSUE THREAD

**Issue by keskink** [SunPointed/MPFlutterChart#81]
textColor not chaning any legent label colors.

I try too many different method for change legent text color for dark mode.
Now legend color is blakc. it can not shown in dark mode.

Regards

**Comment by SunPointed** [comment]
not publish lib yet，are you using project or 0.1.8

**Comment by SunPointed** [comment]
I upload 0.1.9 you can have a try, in my place legend text color can changed

**Comment by keskink** [comment]
I am using 0.1.8 now

**Comment by keskink** [comment]
it worked. Many thanks.
