### ISSUE TITLE
Transparence does not work

### ISSUE THREAD

**Issue by dunght196** [SunPointed/MPFlutterChart#82]
I want to combine 2 Horizontal Bar Chart and Scatter Plot Chart. Although I use Stack to overlap together, 2 charts are put on one background but don't have transparent field => Chart 1 cannot be displayed. I set drawGridBackground: false but it doesn't work. Please give me a solution, thank you.

**Comment by SunPointed** [comment]
set controller's backgroundColor tans can make background tansparence

**Comment by dunght196** [comment]
Hi,
From new updated version 0.1.9, Controller's backgroundColor has been
worked, 0.1.8 is not. Thank you

Vào Th 5, 19 thg 3, 2020 vào lúc 21:37 SunPointed <
notifications@github.com> đã viết:
