### ISSUE TITLE
How to HighLight click show valueformatter change ?

### ISSUE THREAD

**Issue by mergengerel** [SunPointed/MPFlutterChart#87]

**Comment by SunPointed** [comment]
What does show "valueformatter change" mean, did it mean dynamic change the valueformatter when chart is show?

**Comment by mergengerel** [comment]
![image](https://user-images.githubusercontent.com/3488238/77981877-92b8b800-733d-11ea-9688-1477182461bb.png)

I want to drew undrline same valueformat.
Thanks
