### ISSUE TITLE
SelectionListener only working if HighLightPerTapEnabled is enabled

### ISSUE THREAD

**Issue by setime** [SunPointed/MPFlutterChart#9]
If the highLightPerTapEnabled option is disabled the selection listener stops working as well.

**Comment by SunPointed** [comment]
In chart, value only selected when it's highlighting. If you want change this, you may fork and change the 'painter.dart' lines 366 through 373 like below. 
`if (callListener && _selectionListener != null) {
      if (!valuesToHighlight())
        _selectionListener?.onNothingSelected();
      else {
        // notify the listener
        _selectionListener?.onValueSelected(e, high);
      }
    }`
