### ISSUE TITLE
how to make line filled

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#92]
i need help for make this line
https://image.binance.vision/uploads/vYjvZMXUXA9vzO4v5mOy.png
[](https://image.binance.vision/uploads/vYjvZMXUXA9vzO4v5mOy.png)

**Comment by m2faridi** [comment]
Is there a way?

**Comment by SunPointed** [comment]
not support now , this seems difficult to  compute the region of intersection with two line sets

**Comment by m2faridi** [comment]
pls add this
