### ISSUE TITLE
Pie chart custom font not working 

### ISSUE THREAD

**Issue by anwar25** [SunPointed/MPFlutterChart#98]
I am not able to use custom font for piechart . 
Font file extension is .otf 
Below is the method . 

initPieData(List<double> pieEntries) async{

    // NOTE: The order of the entries when being added to the entries array determines their position around the center of
    // the chart.
    for (double pieEntry in pieEntries) {
      entries.add(PieEntry(
        value: pieEntry,
      ));
    }

    PieDataSet dataSet = PieDataSet(entries, "");

    dataSet.setDrawIcons(false);
    //dataSet.setSliceSpace(3);
    //dataSet.setIconsOffset(MPPointF(0, 40));
    dataSet.setSelectionShift(10);
    dataSet.setValueTextSize(15);
    dataSet.setValueTypeface(Utility.CHART_FONT);
    dataSet.setColors1(AppColors.chartColorList);

    _pieChartController.data = PieData(dataSet);
    _pieChartController.data
      ..setValueFormatter(_formatter)
      ..setValueTextColor(ColorUtils.WHITE)
      ..setValueTypeface(Utility.CHART_FONT)
      ..setValueTextSize(15);

  }

class Utility {

  static TypeFace CHART_FONT = TypeFace(fontFamily: "Graphik-Semibold");
}

pubspec.yaml

 fonts:
   
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik/Graphik-Regular.otf
    - family: Graphik-Semibold
      fonts:
      - asset: assets/fonts/Graphik/Graphik-Semibold.otf
    - family: Graphik-Light

**Comment by SunPointed** [comment]
I update version to 0.2.0, fix setValueTypeface and setValueTextSize not work
